FROM python:3.9-windowsservercore-ltsc2022

ENV HY_VERSION 0.24.0
ENV HYRULE_VERSION 0.2

RUN pip install --no-cache-dir ('hy == {0}' -f $env:HY_VERSION) ('hyrule == {0}' -f $env:HYRULE_VERSION)

CMD ["hy"]
