FROM python:3.13-windowsservercore-1809

ENV HY_VERSION 1.0.0
ENV HYRULE_VERSION 0.7.0

RUN pip install --no-cache-dir ('hy == {0}' -f $env:HY_VERSION) ('hyrule == {0}' -f $env:HYRULE_VERSION)

CMD ["hy"]
