FROM pypy:3.8-windowsservercore-ltsc2022

ENV HY_VERSION 0.26.0
ENV HYRULE_VERSION 0.3.0

RUN pip install --no-cache-dir ('hy == {0}' -f $env:HY_VERSION) ('hyrule == {0}' -f $env:HYRULE_VERSION)

CMD ["hy"]
