FROM python:3.9-windowsservercore-ltsc2022

ENV HY_VERSION 1.0a4
ENV HYRULE_VERSION 0.1

RUN pip install --no-cache-dir ('hy == {0}' -f $env:HY_VERSION) ('hyrule == {0}' -f $env:HYRULE_VERSION)

CMD ["hy"]
